[package]
name = "picow"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"

[dependencies.winapi]
version = "0.3.9"
features = ["consoleapi", "handleapi", "processenv", "winbase", "wincon", "impl-default"]
